### ISSUE TITLE
Lumen VegaLite sometimes inserts <class 'lumen.views.base.VegaLiteView'>

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#1076]
Sometimes it's nested like:
```yaml
max_width: 1200
min_height: 300
pipeline:
  source:
    tables:
      category_5_hurricane_trajectories: |-
        SELECT
          *
        FROM READ_PARQUET('/Users/ahuang/repos/lumen/tc_tracks.parquet') AS tc_tracks
        WHERE
          "usa_sshs" = 5
    type: duckdb
    uri: ':memory:'
  sql_transforms:
  - limit: 1000000
    type: sql_limit
  table: category_5_hurricane_trajectories
sizing_mode: stretch_both
spec:
  $schema: https://vega.github.io/schema/vega-lite/v5.json
  height: container
  max_width: 1200
  min_height: 300
  sizing_mode: stretch_both
  spec:
    $schema: https://vega.github.io/schema/vega-lite/v5.json
    data:
      format:
        type: json
      url: data/your_data_source_here
    description: Trajectories of Category 5 hurricanes.
    encoding:
      color:
        field: name
        title: Hurricane Name
        type: nominal
      tooltip:
      - field: iso_time
        title: Time
        type: temporal
      - field: lat
        title: Latitude
        type: quantitative
      - field: lon
        title: Longitude
        type: quantitative
      x:
        field: lon
        title: Longitude
        type: quantitative
      y:
        field: lat
        title: Latitude
        type: quantitative
    height: container
    mark: line
    transform:
    - as: datetime
      calculate: datetime(datum.iso_time)
    width: container
  type: <class 'lumen.views.base.VegaLiteView'>
  width: container
type: vegalite
```

The correct version is:

```yaml
max_width: 1200
min_height: 300
pipeline:
  source:
    tables:
      category_5_hurricanes: |-
        SELECT
          *
        FROM READ_PARQUET('/Users/ahuang/repos/lumen/tc_tracks.parquet')
        WHERE
          "usa_sshs" = 5
    type: duckdb
    uri: ':memory:'
  sql_transforms:
  - limit: 1000000
    type: sql_limit
  table: category_5_hurricanes
sizing_mode: stretch_both
spec:
  $schema: https://vega.github.io/schema/vega-lite/v5.json
  config:
    line:
      interpolate: monotone
  data:
    format:
      type: json
    url: data/category_5_hurricanes.json
  description: Trajectories of Category 5 Hurricanes
  encoding:
    color:
      field: name
      title: Hurricane Name
      type: nominal
    tooltip:
    - field: name
      title: Hurricane Name
      type: nominal
    - field: usa_wind
      title: Wind Speed (mph)
      type: quantitative
    - field: iso_time
      title: Date and Time
      type: temporal
    x:
      field: iso_time
      title: Date and Time
      type: temporal
    y:
      field: lat
      title: Latitude
      type: quantitative
  height: container
  mark: line
  width: container
type: vegalite
```

Haven't been able to reproduce it consistently:
1. Find all Category 5 Hurricanes
2. Plot all their trajectories separately

<img width="838" alt="Image" src="https://github.com/user-attachments/assets/45728f8d-4876-4ece-bc3d-7facf153716d" />

**Comment by ahuang11** [comment]
```yaml
max_width: 1200
min_height: 300
pipeline:
  source:
    tables:
      category_5_hurricane_trajectories: |-
        SELECT
          *
        FROM READ_PARQUET('/Users/ahuang/repos/lumen/tc_tracks.parquet') AS tc_tracks
        WHERE
          "usa_sshs" = 5
    type: duckdb
    uri: ':memory:'
  sql_transforms:
  - limit: 1000000
    type: sql_limit
  table: category_5_hurricane_trajectories
sizing_mode: stretch_both
spec:
  $schema: https://vega.github.io/schema/vega-lite/v5.json
  height: container
  max_width: 1200
  min_height: 300
  sizing_mode: stretch_both
  spec:
    $schema: https://vega.github.io/schema/vega-lite/v5.json
    data:
      format:
        type: json
      url: data/your_data_source_here
    description: Trajectories of Category 5 hurricanes.
    encoding:
      color:
        field: name
        title: Hurricane Name
        type: nominal
      tooltip:
      - field: iso_time
        title: Time
        type: temporal
      - field: lat
        title: Latitude
        type: quantitative
      - field: lon
        title: Longitude
        type: quantitative
      x:
        field: lon
        title: Longitude
        type: quantitative
      y:
        field: lat
        title: Latitude
        type: quantitative
    height: container
    mark: line
    transform:
    - as: datetime
      calculate: datetime(datum.iso_time)
    width: container
  type: <class 'lumen.views.base.VegaLiteView'>
  width: container
type: vegalite
```
