### ISSUE TITLE
Prompt LLM to use a coastal layer if plotting a map

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#1077]
This generates a map
```
    - data:
        url: https://vega.github.io/vega-datasets/data/world-110m.json
        format:
          type: topojson
          feature: countries
      mark:
        type: geoshape
        fill: null
        stroke: "#aaa"
      projection:
        type: mercator
```

![Image](https://github.com/user-attachments/assets/b174a4d7-579c-479c-ba11-91fab8487bdd)

Just need to figure out how to overlay

**Comment by ahuang11** [comment]
```yaml
max_width: 1200
min_height: 300
pipeline:
  source:
    tables:
      lat_lon_map: |-
        SELECT
          *
        FROM READ_PARQUET('/Users/ahuang/repos/lumen/tc_tracks.parquet');
    type: duckdb
    uri: ':memory:'
  sql_transforms:
  - limit: 1000000
    type: sql_limit
  table: lat_lon_map
sizing_mode: stretch_both
spec:
  $schema: https://vega.github.io/schema/vega-lite/v5.json
  data:
    format:
      type: json
    url: data/lat_lon_map
  description: A map visualization of latitude and longitude data.
  height: 400
  layer:
  - data:
      format:
        feature: countries
        type: topojson
      url: https://vega.github.io/vega-datasets/data/world-110m.json
    mark:
      fill: lightgray
      type: geoshape
  - encoding:
      latitude:
        field: lat
        type: quantitative
      longitude:
        field: lon
        type: quantitative
      tooltip:
      - field: name
        type: nominal
      - field: usa_status
        type: nominal
    mark: circle
  projection:
    type: mercator
  width: 800
type: vegalite

```
