### ISSUE TITLE
`get_schema` enum limitation due to 1000 rows fetched only

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#1084]
Just marking this so I don't forget to investigate...

I was asking it:
`What are all the Category 5 hurricanes in the Atlantic since 2000?`

```
Schema:
```yaml
basin:
  enum:
  - SP
  - SI
  - WP
  type: str
```

The dataset should have more than just these three, and should have an ellipses. For enums I think we should include unique value count.
