### ISSUE TITLE
Issues with numerical filtering

### ISSUE THREAD

**Issue by jbednar** [holoviz/lumen#126]
If I include a numerical column like `flipper_length_mm` as a filter widget using lumen=0.4.0a2.post2+g0c9fcc3, I get a very reasonable-looking widget but a very unreasonable looking plot

```
config:
  title: Palmer Penguins
sources:
  penguins:
    type: file
    tables:
      penguins: https://tinyurl.com/lumen21/penguins.csv
targets:
  - title: Palmer penguin
    source: penguins
    filters:
      - type: widget
        field: species
      - type: widget
        field: flipper_length_mm
    views:
      scatter:
        type: hvplot
        table: penguins
        kind: scatter
        x: bill_length_mm
        y: bill_depth_mm
        color: species
        responsive: true
        height: 500
        selection_group: penguin
    sizing_mode: stretch_both
```

![image](https://user-images.githubusercontent.com/1695496/114649198-a9f6e900-9ca5-11eb-9a27-28f3b7cc9a05.png)

If I take that widget out I get a very reasonable looking plot:

![image](https://user-images.githubusercontent.com/1695496/114649237-bbd88c00-9ca5-11eb-94b3-22ab93803782.png)

Am I making some silly error? Seems to work fine for categorical values and for `year` (an integer), but not for floats.
