### ISSUE TITLE
Data Refresh Breaks Layout Styling

### ISSUE THREAD

**Issue by tlmille2** [holoviz/lumen#142]
When you first load into a Lumen dashboard using a layout configuration for the views, the dashboard maintains the styling of those components.
![image](https://user-images.githubusercontent.com/36211553/115710934-8af8f680-a338-11eb-979b-7e4135dd81b1.png)

When you click the data refresh button, the layout is ignored and you see the following view:
![image](https://user-images.githubusercontent.com/36211553/115711503-34d88300-a339-11eb-95ad-df75b204e743.png)
![image](https://user-images.githubusercontent.com/36211553/115711618-5afe2300-a339-11eb-8c7b-33fc96253715.png)

Example `dashboard.yml` configuration. 
```yaml
config:
  title: "Example Dashboard"
sources:
  dremio:
    type: intake
    shared: true
    cache_dir: cache
    uri: catalog.yml
targets:
       
  - title: Stuff
    source: dremio
    views:
      View1:
        table: dremio_vds
        type: trend
        y: y1
      View2:
        table: dremio_vds
        type: trend
        y: y2
      View3:
        table: dremio_vds
        type: trend
        y: y3
      View4:
        table: dremio_vds
        type: trend
        y: y4
      View5:
        table: dremio_vds
        type: heatmap_weekly
      View6:
        table: dremio_vds
        type: thing
        y: y6
        variable: 60

    layout: [["View1", "View2", "View3", "View4"], ["View5", "View6"]]
    sizing_mode: stretch_width
```
