### ISSUE TITLE
Enable Functionality to Auto Update Cached Data

### ISSUE THREAD

**Issue by tlmille2** [holoviz/lumen#143]
When you serve a dashboard using `lumen serve dashboard.yml --warm` and the following source configuration:

```yaml
sources:
  dremio:
    type: intake
    shared: true
    cache_dir: cache
    uri: catalog.yml
```

The data is cached in a cache directory on the first instantiation of the dashboard.  When you resolve the DNS in subsequent visits, the data then is pulled directly from the cache directory, and not updated.  The only way to update the data in the cache, is to click the icon to refresh the data.

The to-be feature request would be to enable a process to run autonomously to pull in new data at a defined interval.

For example in the `dashboard.yaml`:

```yaml
sources:
  dremio:
    type: intake
    shared: true
    cache_dir: cache
    cache_refresh: 1h
    uri: catalog.yml
```
