### ISSUE TITLE
Filters first appeared as shared while they should not

### ISSUE THREAD

**Issue by maximlt** [holoviz/lumen#190]
Create some data with:
```python
import pandas as pd
import numpy as np
SIZE = 1000
df = pd.DataFrame(
    {
        'd': np.arange(SIZE),
        'x': np.random.choice(list('abc'), size=SIZE),
        'y': np.random.choice(list('def'), size=SIZE),
        'z': np.random.choice(list('ghi'), size=SIZE),
        'v': np.random.random(size=SIZE)
    }
)
df.to_csv('data.csv', index=False)
```
And run this app:
```yaml
config:
  title: Palmer Penguins
  theme: dark
  layout: tabs
defaults:
  filters:
    - type: widget
      multi: false
      empty_select: false
sources:
  revenue:
    type: file
    tables:
      revenue: data.csv
    filters:
      xf:
        type: widget
        field: x
        shared: false
        default: a
      yf:
        type: widget
        field: y
        shared: false
        default: d
      zf:
        type: widget
        field: z
        shared: false
        default: g
targets:
  - title: X
    source: revenue
    filters:
      - yf
      - zf
    views:
      scatter:
        type: hvplot
        table: revenue
        kind: scatter
        x: d
        y: v
        color: x
        width: 350
        height: 350
  - title: Y
    source: revenue
    filters:
      - xf
      - zf
    views:
      scatter:
        type: hvplot
        table: revenue
        kind: scatter
        x: d
        y: v
        color: y
        width: 350
        height: 350
  - title: Z
    source: revenue
    filters:
      - xf
      - yf
    views:
      scatter:
        type: hvplot
        table: revenue
        kind: scatter
        x: d
        y: v
        color: z
        width: 350
        height: 350
    sizing_mode: stretch_width
```

The three filters xh, yf and zf are declared are not shared, but when the app is launched yf and zf show up as shared.
<img width="804" alt="image" src="https://user-images.githubusercontent.com/35924738/135503906-190fb0f3-e244-428f-affe-613394629365.png">

It's only after clicking on the Y and Z tabs that the app filters get updated and stop showing up as shared.
<img width="809" alt="image" src="https://user-images.githubusercontent.com/35924738/135504104-be9adb92-0258-4dbc-8c7d-f927f823d1ba.png">
