### ISSUE TITLE
Add ability to template variables

### ISSUE THREAD

**Issue by philippjfr** [holoviz/lumen#21]
Lumen yaml specifications should provide the ability to supply arguments which are templated into the yaml file on the commandline. This is particularly important for passwords or other information which should not be stored in the yaml, e.g.

```yaml
config:
  title: "AE5 Monitor"
  ncols: 3
targets:
  - title: PyViz
    source:
        type: join
        sources:
          ae5:
            type: ae5
            url: pyviz.demo.anaconda.com
            kubernetes_api: https://kube-control.pyviz.demo.anaconda.com
            username: anaconda-enterprise
            password: {ae5_password}
```

Should allow something like:

```bash
lumen serve dashboard.yaml --ae5_password ...
```

or:

```bash
lumen serve dashboard.yaml --template-vars="{'ae5_password': ...}"
```
