### ISSUE TITLE
Update views in parallel

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/lumen#310]
Right now, if you update a filter, each view is updated in serial; see the video below. It could be nice if the views update in somewhat parallel.  

https://user-images.githubusercontent.com/19758978/187155822-1c9a8830-abdb-4ee7-995f-cf17b6549642.mp4

``` yaml
sources:
  penguins:
    type: file
    tables:
      penguins: https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv

targets:
  - title: Penguins
    source: penguins
    layout: [[0], [1, 2, 3], [4]]
    filters:
      - type: widget
        field: sex
      - type: widget
        field: island
    views:
      - type: hvplot
        tables: penguins
        kind: scatter
        x: bill_length_mm
        y: bill_depth_mm
        selection_group: a
        responsive: true
        height: 350
      - type: hvplot
        tables: penguins
        kind: hist
        y: bill_length_mm
        responsive: true
        height: 350
        selection_group: a
      - type: hvplot
        tables: penguins
        kind: hist
        y: bill_depth_mm
        responsive: true
        height: 350
        selection_group: a
      - type: hvplot
        tables: penguins
        kind: hist
        y: body_mass_g
        responsive: true
        height: 350
        selection_group: a
      - type: table
        table: penguins
        height: 300
        selection_group: a
    sizing_mode: stretch_width
```
