### ISSUE TITLE
Reload not reloading

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/lumen#318]
When trying to reload a source the animation is stuck on `Reloading Table ...`. 

``` yaml
sources:
  penguins:
    type: file
    tables:
      penguins: https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv

targets:
  - title: Table
    source: penguins
    views:
      - type: table
        table: penguins
```

https://user-images.githubusercontent.com/19758978/188854963-6ce9f3af-3329-45b8-9ca7-5571a295834e.mp4
