### ISSUE TITLE
defaults cannot be set

### ISSUE THREAD

**Issue by droumis** [holoviz/lumen#337]
#### ALL software version info
lumen: 0.5.0a64

#### Description of expected behavior and the observed behavior
defaults should be applied to relevant object

#### Complete, minimal, self-contained example code that reproduces the issue
`penguin.yaml`
```
defaults:
  filters:
    - type: widget
      multi: false

config:
  title: Palmer Penguins
  theme: dark

sources:
  penguin_source:
    type: file
    tables:
      penguin_table: https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-28/penguins.csv

pipelines:
  penguin_pipeline:
    source: penguin_source
    table: penguin_table
    filters:
      - type: widget
        field: sex
      - type: widget
        field: island
    transforms:
      - type: columns
        columns: ['species', 'island', 'sex', 'year', 'bill_length_mm', 'bill_depth_mm']

targets:
  - title: Penguins
    pipeline: penguin_pipeline
    layout: [[0], [1, 2]]
    sizing_mode: stretch_width
    height: 800
    views:
      - type: hvplot
        x: bill_length_mm
        y: bill_depth_mm
        kind: scatter
        color: species
        responsive: true
        height: 400
      - type: hvplot
        kind: hist
        y: bill_length_mm
        responsive: true
        height: 300
      - type: table
        show_index: false
        height: 300
```

#### Stack traceback and/or browser JavaScript console output
>> lumen serve --show penguin.yaml
`ERROR: 'type' is not a parameter of WidgetFilter`
