### ISSUE TITLE
Enabling `sync_with_url` does not sync with Filters after reload

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/lumen#456]
Enabling `sync_with_url` does not sync with Filter after reload

Update the config to the following:
``` yaml
config:
  title: Altair Seattle Weather
  reloadable: false
  sync_with_url: true
```

And comment out margin because of #454

Then change the weather to `fog` and reload the page:

https://user-images.githubusercontent.com/19758978/227920697-be803a84-bdb4-4c24-927a-6aa932fa4829.mp4
