### ISSUE TITLE
Should RESTSource be renamed to LumenRESTSource?

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#510]
I was trying to use it like this:
https://docs.aviationapi.com/#tag/charts

```yaml
sources:
  aviation_source:
    type: rest
    url: https://api.aviationapi.com/v1/charts?apt=KCMI
 
layouts:
  - title: Aviation
    source: aviation_source
    views:
      - type: hvplot_ui
```

But I realized it's specifically an endpoint for hosting Lumen specs
"""
RESTSource allows querying REST endpoints conforming to the Lumen REST specification.

The url must offer two endpoints, the /data endpoint must return data in a records format while the /schema endpoint must return a valid Lumen JSON schema.
"""

**Comment by ahuang11** [comment]
For reference, this works to a point, but I need to figure out how to subset a key.
```
sources:
  aviation_source:
    type: json
    tables:
      kcmi_chart: https://api.aviationapi.com/v1/charts?apt=KCMI
 
layouts:
  - title: Aviation
    source: aviation_source
    views:
      - type: hvplot_ui
        table: kcmi_chart
```
