### ISSUE TITLE
Cannot add Lumen dashboards dynamically to Panel layouts

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#513]
Not sure if this should reside in Panel or Lumen.

I've tried as a ChatMessage:
```python
import panel as pn
import lumen as lm
import yaml
pn.extension()

def callback(contents, user, instance):
    with open("test.yaml", "r") as f:
        spec = yaml.safe_load(f)
    dashboard = lm.Dashboard(spec)
    return


tabs = pn.Tabs(("Chat", pn.chat.ChatInterface(callback=callback)))
tabs.servable()
```

Tabs:
```python
import panel as pn
import lumen as lm
import yaml
pn.extension()

def callback(contents, user, instance):
    with open("test.yaml", "r") as f:
        spec = yaml.safe_load(f)
    dashboard = lm.Dashboard(spec)
    tabs.append(("Dashboard", dashboard))


tabs = pn.Tabs(("Chat", pn.chat.ChatInterface(callback=callback)))
tabs.servable()
```

It just displays an empty dashboard

<img width="1339" alt="image" src="https://github.com/holoviz/lumen/assets/15331990/a83cc58d-4dd6-4a6a-a2d6-5b6c3af7b7db">

I suspect it might be lazily loading and not trigger because I tried to extract the layout, but it crashes with list index out of range.
```python
import panel as pn
import lumen as lm
import yaml
pn.extension()

def callback(contents, user, instance):
    with open("test.yaml", "r") as f:
        spec = yaml.safe_load(f)
    dashboard = lm.Dashboard(spec).layouts[0]
    return dashboard


tabs = pn.Tabs(("Chat", pn.chat.ChatInterface(callback=callback)))
tabs.servable()
```

test.yaml
```yaml
sources:
  penguin_source:
    type: file
    tables:
      penguin_table: https://datasets.holoviz.org/penguins/v1/penguins.csv

layouts:
  - title: Penguins
    source: penguin_source
    views:
      - type: table
        table: penguin_table
```
