### ISSUE TITLE
Spatial filter from map tools

### ISSUE THREAD

**Issue by yougis** [holoviz/lumen#80]
For now filterWidget works well with fields values. 
I suggest to go throught filtering sources by spatial query. 
For example, when a source is a geodataframe we might draw polygon on a small map that can perform a spatial intersect on the source. 
For exemple we should declare on the spec ’s filter section something like this:

```yaml
Filters:
- type : spatial
  method : intersect / contain
  opposit : False 
  tools : [box, tap, lasso,  line?]
  buffer : 
     distance : 10 
     unit : meters / miles /  nautic_mile / decimal_degres
  tile : EsriImagery
  Epsg : 3857
  InitialExtent: from_source / [bbox] / global
```
Methods could be inspired by  that [reference](https://www.sciencedirect.com/science/article/pii/S1474034609000287)
 Obviously, lumen should depends on spatial libs like cartopy,  geoviews and geopandas or spatialpandas...
