### ISSUE TITLE
Empty vega plot if spec has invalid param

### ISSUE THREAD

**Issue by ahuang11** [holoviz/lumen#900]
The offending line is:
```

      scale:
        scheme: diverging
```

```yaml
min_height: 500
pipeline:
  source:
    tables:
      normalized_totals_passengers_flights: "WITH cleaned_passengers AS (\n    SELECT\n\
        \        \"Year\",\n        \"Month\",\n        TRY_CAST(REPLACE(REPLACE(\"\
        TOTAL\", ',', ''), ' ', '') AS INTEGER) AS total_passengers\n    FROM read_csv('passengers.csv')\n\
        ),\ncleaned_flights AS (\n    SELECT\n        \"Year\",\n        \"Month\"\
        ,\n        TRY_CAST(REPLACE(REPLACE(\"TOTAL\", ',', ''), ' ', '') AS INTEGER)\
        \ AS total_flights\n    FROM read_csv('flights.csv')\n),\njoined_data AS (\n\
        \    SELECT\n        p.\"Year\",\n        COALESCE(p.total_passengers, 0)\
        \ AS total_passengers,\n        COALESCE(f.total_flights, 0) AS total_flights\n\
        \    FROM cleaned_passengers p\n    JOIN cleaned_flights f ON p.\"Year\" =\
        \ f.\"Year\"\n)\nSELECT\n    \"Year\",\n    total_passengers,\n    total_flights,\n\
        \    total_passengers * 1.0 / MAX(total_passengers) OVER () AS normalized_passengers,\n\
        \    total_flights * 1.0 / MAX(total_flights) OVER () AS normalized_flights\n\
        FROM joined_data"
    type: duckdb
    uri: ':memory:'
  sql_transforms:
  - limit: 1000000
    type: sql_limit
  table: normalized_totals_passengers_flights
sizing_mode: stretch_both
spec:
  $schema: https://vega.github.io/schema/vega-lite/v5.json
  data:
    url: data/normalized_totals_passengers_flights.csv
  description: A scatter plot showing the relationship between normalized passengers
    and normalized flights, colored by year using a diverging colormap.
  encoding:
    color:
      field: Year
      scale:
        scheme: diverging
      title: Year
      type: ordinal
    tooltip:
    - field: Year
      type: ordinal
    - field: normalized_passengers
      type: quantitative
    - field: normalized_flights
      type: quantitative
    x:
      field: normalized_passengers
      title: Normalized Passengers
      type: quantitative
    y:
      field: normalized_flights
      title: Normalized Flights
      type: quantitative
  height: container
  mark: point
  title: Relationship Between Normalized Passengers and Normalized Flights by Year
  width: container
type: vegalite

```

<img width="1482" alt="Image" src="https://github.com/user-attachments/assets/9b7e6ce3-2336-4a55-baa3-4ffa7be6f874" />
